---

homebrew:
  packages:
    - ansible
    # - awless
    - awscli
    - antibody
    - bat
    - bottom
    - exa
    - fd
    - fzf
    - gradle
    - git
    # - go
    - groovy
    - httpie
    # - jq
    # - jrnl
    # - derailed/k9s/k9s
    # - kubectl
    - logitech-options
    - maven
    # - minikube
    - neovim
    - node
    - nvm
    - prettyping
    # - procs
    - python
    # - rustup
    - speedtest-cli
    # - task
    # - tasksh
    - terraform
    # - the_silver_searcher
    - thefuck
    - tldr
    # - tmux
    - tree
    - yarn
    - zsh
  casks:
    - AdoptOpenJDK/openjdk
    - clementtsang/bottom
    - homebrew/cask-drivers
    - homebrew/cask-fonts
    # - wallix/awless
  applications:
    - adoptopenjdk8 
    - adoptopenjdk11
    - discord
    # - dashlane
    - docker
    - firefox
    # - font-hack-nerd-font
    # - hyper
    - google-chrome
    - iterm2
    - jetbrains-toolbox
    # - kap
    # - keybase
    - lastpass
    # - ngrok
    - pingplotter
    - postman
    - rectangle
    - slack
    - spotify
    - tuple
    # - spotmenu
    # - vagrant
    # - virtualbox
    - visual-studio-code
    - zoomus
